<?php

declare(strict_types=1);

namespace RAN\WPReleaseUpdater\V1\WordPress;

use InvalidArgumentException;
use RAN\WPReleaseUpdater\V1\Archive\PackageIdentityValidator;
use RAN\WPReleaseUpdater\V1\Contract\AcquisitionReceipt;
use RAN\WPReleaseUpdater\V1\Contract\BindingRecord;
use RAN\WPReleaseUpdater\V1\Contract\CanonicalUpdateUri;
use RAN\WPReleaseUpdater\V1\Contract\IdentityDescriptor;
use RAN\WPReleaseUpdater\V1\Contract\ReleaseVersion;

/** The single native WordPress lifecycle owner for a sealed neutral release. */
final class NativePluginUpdater {
	private const MAX_DIAGNOSTICS = 16;
	private const MAX_MANIFEST_ENTRIES = 10000;
	private const CONFIGURATION_KEYS = array( 'headers', 'installed_package_identity', 'policy', 'target_type', 'update_uri' );
	private const HEADER_KEYS = array( 'Author', 'Description', 'Name', 'PluginURI', 'RequiresPHP', 'RequiresWP', 'UpdateURI', 'Version' );
	private bool $registered = false;
	private bool $inspectionVerified = false;
	private bool $pending = false;
	private bool $extractionAdmitted = false;
	private ?string $stagedSource = null;
	/** @var array<string,array{sha256:string,size:int}>|null */ private ?array $stagedManifest = null;
	private ?string $pendingArchive = null;
	private ?string $ownedArchiveDirectory = null;
	/** @var array<string,int>|null */ private ?array $pendingArchiveIdentity = null;
	private bool $installResultCaptured = false;
	private mixed $installResult = null;
	private bool $completionObserved = false;
	private bool $multiRun = false;
	private bool $queuedMultiRun = false;
	private bool $shutdownScheduled = false;
	/** @var list<string> */ private array $diagnostics = array();
	/** @var null|callable(BindingState,int):array<string,mixed> */ private $acquire;
	private ?AcquisitionReceipt $pendingReceipt = null;

	/** @param array<string,string> $headers */
	private function __construct( private IdentityDescriptor $descriptor, private string $targetType, private string $installedIdentity, private string $updateUri, private string $policy, private array $headers, private string $bindingHash, private object $wpdb, private BindingState $state, private mixed $claim, ?callable $acquire ) { $this->acquire = $acquire; $this->inspectionVerified = true; }

	/** @param array<string,mixed> $configuration */
	public static function fromConfiguration( array $configuration, IdentityDescriptor $descriptor, BindingRecord $binding, object $wpdb, BindingState $state, mixed $claim, AcquisitionReceipt $inspectionReceipt, ?callable $acquire = null ): ?self {
		if ( ! self::validConfiguration( $configuration, $descriptor ) || ! self::sameBinding( $binding, $state ) || $configuration['policy'] !== $binding->toArray()['update_policy'] ) return null;
		$verified = ReleaseOperationCoordinator::verifyPersistentBindingState( $wpdb, $state, $claim ); if ( 'verified' !== $verified['result'] || ! $verified['current'] instanceof BindingState || ! is_int( $verified['now'] ?? null ) ) return null;
		try { BindingRecord::assertDescriptorBinding( $descriptor, $binding ); AcquisitionReceipt::acceptFresh( $inspectionReceipt, $verified['current'], $descriptor, $verified['now'] ); } catch ( InvalidArgumentException ) { return null; }
		$verified = ReleaseOperationCoordinator::verifyPersistentBindingState( $wpdb, $state, $claim ); if ( 'verified' !== $verified['result'] || ! $verified['current'] instanceof BindingState ) return null;
		$uri = CanonicalUpdateUri::canonicalize( $configuration['update_uri'] );
		return is_string( $uri ) ? new self( $descriptor, $configuration['target_type'], $configuration['installed_package_identity'], $uri, $configuration['policy'], $configuration['headers'], $binding->bindingHash(), $wpdb, $verified['current'], $claim, $acquire ) : null;
	}

	public function register(): void {
		if ( $this->registered ) return;
		$host = parse_url( $this->updateUri, PHP_URL_HOST ); if ( ! is_string( $host ) || '' === $host ) return;
		add_filter( ( 'plugin' === $this->targetType ? 'update_plugins_' : 'update_themes_' ) . $host, array( $this, 'filterUpdate' ), 10, 4 );
		if ( 'plugin' === $this->targetType ) add_filter( 'plugins_api', array( $this, 'filterPluginInformation' ), 10, 3 );
		add_filter( 'plugin' === $this->targetType ? 'auto_update_plugin' : 'auto_update_theme', array( $this, 'filterAutoUpdate' ), 10, 2 );
		add_filter( 'upgrader_package_options', array( $this, 'capturePackageOptions' ), PHP_INT_MAX, 1 ); add_filter( 'upgrader_pre_download', array( $this, 'filterPreDownload' ), PHP_INT_MAX, 4 ); add_filter( 'upgrader_pre_install', array( $this, 'filterPreInstall' ), 1, 2 ); add_filter( 'pre_unzip_file', array( $this, 'filterPreUnzipFile' ), PHP_INT_MAX, 5 ); add_filter( 'upgrader_source_selection', array( $this, 'filterSourceSelection' ), PHP_INT_MAX, 4 ); add_filter( 'upgrader_install_package_result', array( $this, 'captureInstallPackageResult' ), PHP_INT_MAX, 2 ); add_action( 'upgrader_process_complete', array( $this, 'observeCompletion' ), 10, 2 ); $this->registered = true;
	}

	/** @param array<string,mixed>|false $update @param array<string,mixed> $packageData @param list<string> $locales */
	public function filterUpdate( mixed $update, array $packageData, string $packageIdentity, array $locales ): mixed {
		unset( $locales ); if ( ! hash_equals( $this->installedIdentity, $packageIdentity ) ) return $update;
		$installed = is_string( $packageData['Version'] ?? null ) ? $packageData['Version'] : ''; $runtimeUri = is_string( $packageData['UpdateURI'] ?? null ) ? $packageData['UpdateURI'] : '';
		if ( null === ReleaseVersion::normalizeHeader( $installed ) || ! $this->matchesRuntimeUri( $runtimeUri ) ) return $this->diagnose( 'runtime_package_identity_invalid', $update );
		$facts = $this->descriptor->toArray(); if ( ! $this->directFilesystem() || null === $this->verifyCurrent() || ! $this->manualEligible() || ReleaseVersion::RELATIONSHIP_NEWER !== ReleaseVersion::relationship( $facts['version'], $installed ) ) return $update;
		if ( in_array( $this->policy, array( 'disabled', 'forced-off' ), true ) ) return false;
		$offer = array( 'id' => $this->updateUri, 'slug' => $this->informationSlug(), 'url' => $this->updateUri, 'package' => '', 'requires' => $this->headers['RequiresWP'], 'requires_php' => $this->headers['RequiresPHP'], 'version' => $facts['version'], 'autoupdate' => $this->automaticEligible(), 'ran_wp_release_updater_binding_hash' => $this->bindingHash ); if ( 'plugin' === $this->targetType ) $offer['plugin'] = $this->installedIdentity; else $offer['theme'] = $this->installedIdentity; return $offer;
	}

	public function filterPluginInformation( mixed $result, string $action, mixed $arguments ): mixed {
		if ( 'plugin_information' !== $action || ! is_object( $arguments ) || $this->informationSlug() !== ( $arguments->slug ?? null ) || ! $this->directFilesystem() || null === $this->verifyCurrent() || ! $this->manualEligible() ) return $result;
		$facts = $this->descriptor->toArray(); $info = new \stdClass(); $info->name = $this->headers['Name']; $info->slug = $this->informationSlug(); $info->version = $facts['version']; $info->author = $this->headers['Author']; $info->homepage = $this->headers['PluginURI']; $info->requires = $this->headers['RequiresWP']; $info->requires_php = $this->headers['RequiresPHP']; $info->download_link = ''; $info->external = true; $info->sections = array( 'description' => $this->headers['Description'], 'changelog' => '' ); return $info;
	}

	public function filterAutoUpdate( ?bool $update, mixed $item ): ?bool { if ( ! is_object( $item ) || ! $this->matchesItemIdentity( $item ) ) return $update; return ! $this->directFilesystem() || null === $this->verifyCurrent() ? false : $this->automaticEligible(); }

	/** @param array<string,mixed> $hookExtra */
	public function capturePackageOptions( mixed $options ): mixed { $extra = is_array( $options ) && is_array( $options['hook_extra'] ?? null ) ? $options['hook_extra'] : null; if ( is_array( $extra ) && $this->matchesCompletion( $extra ) ) $this->queuedMultiRun = true === ( $options['is_multi'] ?? false ); return $options; }
	/** @param array<string,mixed> $hookExtra */
	public function filterPreDownload( mixed $reply, string $package, mixed $upgrader, array $hookExtra ): mixed {
		unset( $package, $upgrader ); if ( ! $this->matchesOperation( $hookExtra ) ) return $reply; $queuedMultiRun = $this->queuedMultiRun; $this->queuedMultiRun = false; if ( $reply instanceof \WP_Error ) return $reply; if ( false !== $reply ) return $this->failure( 'unverified_pre_download_result' ); $this->clearPending(); if ( ! $this->directFilesystem() || ! $this->inspectionVerified || ! is_callable( $this->acquire ) ) return $this->failure( 'unverified_pre_download' );
		$verified = $this->verifyCurrent(); if ( null === $verified ) return $this->failure( 'binding_fence_lost' ); try { $handoff = ( $this->acquire )( $verified['current'], $verified['now'] ); } catch ( \Throwable ) { return $this->failure( 'acquisition_failed' ); }
		if ( ! self::exactKeys( $handoff, array( 'path', 'receipt' ) ) || ! is_string( $handoff['path'] ) || ! $handoff['receipt'] instanceof AcquisitionReceipt || ! self::matchesArchive( $handoff['path'], $this->descriptor ) ) return $this->failure( 'acquisition_identity_invalid' );
		try { AcquisitionReceipt::assertFresh( $handoff['receipt'], $verified['current'], $this->descriptor, $verified['now'] ); } catch ( InvalidArgumentException ) { return $this->failure( 'acquisition_receipt_invalid' ); }
		$owned = $this->copyOwnedArchive( $handoff['path'] ); if ( null === $owned ) return $this->failure( 'acquisition_identity_invalid' ); $identity = self::archiveIdentity( $owned['path'], $this->descriptor ); if ( null === $identity ) { $this->removeOwnedArchive( $owned['path'], $owned['directory'] ); return $this->failure( 'acquisition_identity_invalid' ); } $this->state = $verified['current']; $this->pendingReceipt = $handoff['receipt']; $this->pending = true; $this->multiRun = $queuedMultiRun; $this->queuedMultiRun = false; $this->pendingArchive = $owned['path']; $this->ownedArchiveDirectory = $owned['directory']; $this->pendingArchiveIdentity = $identity; $this->scheduleFinalization(); return $owned['path'];
	}

	/** @param list<string> $neededDirs */
	public function filterPreUnzipFile( mixed $pre, string $file, string $destination, array $neededDirs, float $requiredSpace ): mixed { unset( $destination, $neededDirs, $requiredSpace ); if ( ! $this->pending || ! is_string( $this->pendingArchive ) || ! hash_equals( $this->pendingArchive, $file ) ) return $pre; $verified = $this->verifyCurrent(); if ( ! $this->directFilesystem() || null === $verified || ! is_array( $this->pendingArchiveIdentity ) || ! self::sameArchiveIdentity( $file, $this->descriptor, $this->pendingArchiveIdentity ) || ! $this->pendingReceipt instanceof AcquisitionReceipt ) { $this->clearPending(); return $this->failure( 'archive_changed_before_extraction' ); } try { AcquisitionReceipt::assertFresh( $this->pendingReceipt, $verified['current'], $this->descriptor, $verified['now'] ); } catch ( InvalidArgumentException ) { $this->clearPending(); return $this->failure( 'archive_changed_before_extraction' ); } $this->state = $verified['current']; $this->extractionAdmitted = true; return $pre; }

	/** @param array<string,mixed> $hookExtra */
	public function filterSourceSelection( mixed $source, string $remoteSource, mixed $upgrader, array $hookExtra ): mixed { unset( $remoteSource, $upgrader ); if ( ! $this->matchesOperation( $hookExtra ) ) return $source; $manifest = is_string( $source ) && $this->matchesStagedMetadata( $source ) ? self::regularFileManifest( $source ) : null; $verified = $this->verifyCurrent(); if ( ! $this->directFilesystem() || ! $this->pending || ! $this->extractionAdmitted || null === $verified || ! $this->pendingReceipt instanceof AcquisitionReceipt || ! is_string( $source ) || ! is_array( $manifest ) ) { $this->clearPending(); return $this->failure( 'staged_package_identity_invalid' ); } try { AcquisitionReceipt::assertArchiveManifest( $this->pendingReceipt, $verified['current'], $this->descriptor, $verified['now'], self::manifestHash( $manifest ), count( $manifest ), self::manifestExpandedBytes( $manifest ) ); } catch ( InvalidArgumentException ) { $this->clearPending(); return $this->failure( 'staged_package_identity_invalid' ); } $this->state = $verified['current']; $this->stagedSource = $source; $this->stagedManifest = $manifest; return $source; }
	/** @param array<string,mixed> $hookExtra */
	public function filterPreInstall( mixed $response, array $hookExtra ): mixed { if ( ! $this->matchesOperation( $hookExtra ) ) return $response; $verified = $this->verifyCurrent(); if ( ! $this->directFilesystem() || ! $this->pending || ! $this->extractionAdmitted || null === $verified || ! $this->pendingReceipt instanceof AcquisitionReceipt || $response instanceof \WP_Error ) { $this->clearPending(); return $this->failure( 'unverified_pre_install' ); } try { AcquisitionReceipt::assertFresh( $this->pendingReceipt, $verified['current'], $this->descriptor, $verified['now'] ); } catch ( InvalidArgumentException ) { $this->clearPending(); return $this->failure( 'unverified_pre_install' ); } $this->state = $verified['current']; return $response; }
	/** @param array<string,mixed> $hookExtra */
	public function captureInstallPackageResult( mixed $result, array $hookExtra ): mixed { if ( ! $this->matchesOperation( $hookExtra ) ) return $result; if ( ! $this->pending || $result instanceof \WP_Error || false === $result ) { $this->clearPending(); return $this->failure( 'unverified_install_result' ); } $this->installResultCaptured = true; $this->installResult = $result; return $result; }
	/** @param array<string,mixed> $hookExtra */
	public function observeCompletion( mixed $upgrader, array $hookExtra ): void { unset( $upgrader ); if ( $this->matchesCompletion( $hookExtra ) ) $this->completionObserved = true; }
	/** Finalization is deliberately after Core rollback and backup cleanup. */
	public function finalizePendingInstall(): void { if ( ! $this->pending ) { $this->clearPending(); return; } try { $destination = is_array( $this->installResult ) && is_string( $this->installResult['destination'] ?? null ) ? $this->installResult['destination'] : null; $manifest = is_string( $destination ) ? self::regularFileManifest( $destination ) : null; $verified = $this->verifyCurrent(); $archiveManifestVerified = false; if ( null !== $verified && $this->pendingReceipt instanceof AcquisitionReceipt && is_array( $manifest ) ) { try { AcquisitionReceipt::assertArchiveManifest( $this->pendingReceipt, $verified['current'], $this->descriptor, $verified['now'], self::manifestHash( $manifest ), count( $manifest ), self::manifestExpandedBytes( $manifest ) ); $archiveManifestVerified = true; $this->state = $verified['current']; } catch ( InvalidArgumentException ) { $archiveManifestVerified = false; } } if ( ! $this->installResultCaptured || ( ! $this->completionObserved && ! $this->multiRun ) || ! $archiveManifestVerified || ! is_string( $destination ) || ! is_array( $this->stagedManifest ) || ! is_array( $manifest ) || ! hash_equals( self::manifestHash( $this->stagedManifest ), self::manifestHash( $manifest ) ) || ! $this->matchesStagedMetadata( $destination ) ) { $this->diagnose( 'outcome_uncertain', null ); return; } $completed = ReleaseOperationCoordinator::completePersistentInstall( $this->wpdb, $this->state, $this->claim, $this->pendingReceipt, $this->descriptor ); $this->diagnose( 'completed' === $completed['result'] ? 'update_completed' : 'outcome_uncertain', null ); } finally { $this->clearPending(); } }
	/** @return list<string> */ public function diagnostics(): array { return $this->diagnostics; }
	public function refresh(): void { $this->diagnostics = array(); $this->queuedMultiRun = false; $this->clearPending(); }

	/** @param array<string,mixed> $configuration */
	private static function validConfiguration( array $configuration, IdentityDescriptor $descriptor ): bool {
		if ( ! self::exactKeys( $configuration, self::CONFIGURATION_KEYS ) || ! is_array( $configuration['headers'] ) || ! self::exactKeys( $configuration['headers'], self::HEADER_KEYS ) || ! is_string( $configuration['update_uri'] ) || ! in_array( $configuration['policy'], array( 'disabled', 'forced-off', 'manual', 'automatic' ), true ) || ! self::validNativeIdentity( $configuration['target_type'], $configuration['installed_package_identity'] ) ) return false;
		foreach ( $configuration['headers'] as $header ) if ( ! is_string( $header ) || strlen( $header ) > 8192 ) return false;
		$facts = $descriptor->toArray(); if ( $configuration['target_type'] !== $facts['target_type'] || ! hash_equals( $configuration['installed_package_identity'], $facts['installed_package_identity'] ) || null === ReleaseVersion::normalizeHeader( $configuration['headers']['Version'] ) ) return false;
		return $facts['canonical_update_uri'] === CanonicalUpdateUri::canonicalizeBoundaries( array( 'archive_preflight' => $facts['canonical_update_uri'], 'configuration' => $configuration['update_uri'], 'offer_or_cache' => $configuration['headers']['UpdateURI'], 'staged_package' => $facts['canonical_update_uri'] ) );
	}

	private function matchesRuntimeUri( string $runtimeUri ): bool { return $this->updateUri === CanonicalUpdateUri::canonicalizeBoundaries( array( 'archive_preflight' => $this->descriptor->toArray()['canonical_update_uri'], 'configuration' => $this->updateUri, 'offer_or_cache' => $runtimeUri, 'staged_package' => $this->headers['UpdateURI'] ) ); }
	private function manualEligible(): bool { $facts = $this->descriptor->toArray(); foreach ( array( 'exact_artifact_identity', 'exact_commit_identity', 'exact_reacquisition_supported', 'exact_release_identity', 'repository_identity_stable', 'trusted_digest_source' ) as $fact ) if ( true !== $facts['assurance_facts'][ $fact ] ) return false; return $this->inspectionVerified; }
	private function automaticEligible(): bool { $facts = $this->descriptor->toArray(); return $this->manualEligible() && 'automatic' === $this->policy && true === $facts['assurance_facts']['publication_immutable'] && true === $facts['assurance_facts']['provenance_verified']; }
	private function informationSlug(): string { return 'ran-wp-release-updater-' . substr( hash( 'sha256', $this->targetType . "\0" . $this->installedIdentity ), 0, 24 ); }
	private function matchesItemIdentity( object $item ): bool { $identity = 'plugin' === $this->targetType ? ( $item->plugin ?? null ) : ( $item->theme ?? null ); return is_string( $identity ) && hash_equals( $this->installedIdentity, $identity ); }
	/** @param array<string,mixed> $extra */ private function matchesOperation( array $extra ): bool { $identity = 'plugin' === $this->targetType ? ( $extra['plugin'] ?? null ) : ( $extra['theme'] ?? null ); if ( ! is_string( $identity ) || ! hash_equals( $this->installedIdentity, $identity ) ) return false; return ( ! array_key_exists( 'action', $extra ) || 'update' === $extra['action'] ) && ( ! array_key_exists( 'type', $extra ) || $this->targetType === $extra['type'] ); }
	/** @param array<string,mixed> $extra */ private function matchesCompletion( array $extra ): bool { if ( 'update' !== ( $extra['action'] ?? null ) || $this->targetType !== ( $extra['type'] ?? null ) ) return false; $key = 'plugin' === $this->targetType ? 'plugins' : 'themes'; $single = 'plugin' === $this->targetType ? 'plugin' : 'theme'; $targets = $extra[ $key ] ?? array( $extra[ $single ] ?? null ); return is_array( $targets ) && in_array( $this->installedIdentity, $targets, true ); }
	private function matchesStagedMetadata( string $source ): bool { $source = rtrim( $source, '/\\' ); $directory = @lstat( $source ); if ( ! is_array( $directory ) || 0040000 !== ( $directory['mode'] & 0170000 ) || ! hash_equals( $this->packageRoot(), basename( $source ) ) ) return false; $header = 'plugin' === $this->targetType ? basename( $this->installedIdentity ) : 'style.css'; $path = $source . DIRECTORY_SEPARATOR . $header; $file = @lstat( $path ); if ( ! is_array( $file ) || 0100000 !== ( $file['mode'] & 0170000 ) ) return false; $contents = @file_get_contents( $path, false, null, 0, 8192 ); if ( ! is_string( $contents ) ) return false; $name = self::headerValue( $contents, 'theme' === $this->targetType ? 'Theme Name' : 'Plugin Name' ); $version = self::headerValue( $contents, 'Version' ); $uri = self::headerValue( $contents, 'Update URI' ); $facts = $this->descriptor->toArray(); return is_string( $name ) && hash_equals( $this->headers['Name'], $name ) && is_string( $version ) && is_string( $uri ) && 0 === ReleaseVersion::compare( $version, $facts['version'] ) && $this->matchesRuntimeUri( $uri ); }
	private function packageRoot(): string { return 'plugin' === $this->targetType ? dirname( $this->installedIdentity ) : $this->installedIdentity; }
	private function scheduleFinalization(): void { if ( $this->shutdownScheduled ) return; add_action( 'shutdown', array( $this, 'finalizePendingInstall' ), PHP_INT_MAX, 0 ); $this->shutdownScheduled = true; }
	/** @return array{current:BindingState,now:int}|null */ private function verifyCurrent(): ?array { $verified = ReleaseOperationCoordinator::verifyPersistentBindingState( $this->wpdb, $this->state, $this->claim ); return 'verified' === $verified['result'] && $verified['current'] instanceof BindingState && is_int( $verified['now'] ?? null ) ? array( 'current' => $verified['current'], 'now' => $verified['now'] ) : null; }
	private function clearPending(): void { $this->removeOwnedArchive( $this->pendingArchive, $this->ownedArchiveDirectory ); $this->pending = false; $this->extractionAdmitted = false; $this->stagedSource = null; $this->stagedManifest = null; $this->pendingArchive = null; $this->ownedArchiveDirectory = null; $this->pendingArchiveIdentity = null; $this->pendingReceipt = null; $this->installResultCaptured = false; $this->installResult = null; $this->completionObserved = false; $this->multiRun = false; }
	private function diagnose( string $code, mixed $return ): mixed { if ( count( $this->diagnostics ) === self::MAX_DIAGNOSTICS ) array_shift( $this->diagnostics ); $this->diagnostics[] = $code; return $return; }
	private function failure( string $code ): mixed { $this->diagnose( $code, null ); return class_exists( '\\WP_Error' ) ? new \WP_Error( 'ran_wp_release_updater_' . $code, 'The update operation was not admitted.' ) : false; }
	private function directFilesystem(): bool { return function_exists( 'get_filesystem_method' ) && 'direct' === get_filesystem_method(); }
	/** @return array{directory:string,path:string}|null */ private function copyOwnedArchive( string $source ): ?array {
		$facts = $this->descriptor->toArray(); $before = self::archiveIdentity( $source, $this->descriptor ); if ( null === $before ) return null;
		try { $suffix = bin2hex( random_bytes( 16 ) ); } catch ( \Throwable ) { return null; } $directory = rtrim( sys_get_temp_dir(), '/\\' ) . DIRECTORY_SEPARATOR . 'ran-wp-release-updater-' . $suffix; if ( ! @mkdir( $directory, 0700 ) || ! @chmod( $directory, 0700 ) ) return null;
		$path = $directory . DIRECTORY_SEPARATOR . 'package.zip'; $input = @fopen( $source, 'rb' ); $output = @fopen( $path, 'x+b' ); if ( ! is_resource( $input ) || ! is_resource( $output ) || ! @chmod( $path, 0600 ) ) { if ( is_resource( $input ) ) fclose( $input ); if ( is_resource( $output ) ) fclose( $output ); $this->removeOwnedArchive( $path, $directory ); return null; }
		$context = hash_init( 'sha256' ); $size = 0; $ok = true; while ( ! feof( $input ) ) { $chunk = fread( $input, 65536 ); if ( ! is_string( $chunk ) || ( '' === $chunk && ! feof( $input ) ) || strlen( $chunk ) > $facts['artifact_size'] - $size ) { $ok = false; break; } for ( $written = 0, $length = strlen( $chunk ); $written < $length; ) { $result = fwrite( $output, substr( $chunk, $written ) ); if ( ! is_int( $result ) || 0 === $result ) { $ok = false; break 2; } $written += $result; } $size += $length; hash_update( $context, $chunk ); } fflush( $output ); fclose( $input ); fclose( $output ); clearstatcache( true, $source ); $after = self::archiveIdentity( $source, $this->descriptor ); if ( ! @chmod( $path, 0400 ) ) $ok = false; $copy = self::archiveIdentity( $path, $this->descriptor ); if ( ! $ok || $size !== $facts['artifact_size'] || ! hash_equals( $facts['artifact_sha256'], hash_final( $context ) ) || ! is_array( $after ) || $after !== $before || null === $copy ) { $this->removeOwnedArchive( $path, $directory ); return null; } return array( 'directory' => $directory, 'path' => $path );
	}
	private function removeOwnedArchive( ?string $path, ?string $directory ): void { if ( is_string( $path ) && is_string( $directory ) && hash_equals( $directory . DIRECTORY_SEPARATOR . 'package.zip', $path ) ) { $entry = @lstat( $path ); if ( is_array( $entry ) ) { if ( 0040000 === ( $entry['mode'] & 0170000 ) ) @rmdir( $path ); else @unlink( $path ); } } if ( is_string( $directory ) && is_dir( $directory ) ) @rmdir( $directory ); }
	private static function validNativeIdentity( mixed $type, mixed $identity ): bool { if ( ! is_string( $identity ) ) return false; if ( 'theme' === $type ) return 1 === preg_match( '/\A[A-Za-z0-9][A-Za-z0-9._-]{0,99}\z/D', $identity ); return 'plugin' === $type && 1 === preg_match( '/\A[A-Za-z0-9][A-Za-z0-9._-]{0,99}\/[A-Za-z0-9][A-Za-z0-9._-]{0,99}\.php\z/D', $identity ); }
	private static function sameBinding( BindingRecord $binding, BindingState $state ): bool { return self::sameBindingHash( $binding->bindingHash(), $state ); }
	private static function sameBindingHash( string $hash, BindingState $state ): bool { return hash_equals( $hash, $state->binding()->bindingHash() ); }
	private static function matchesArchive( string $path, IdentityDescriptor $descriptor ): bool { return null !== self::archiveIdentity( $path, $descriptor ); }
	/** @return array<string,int>|null */ private static function archiveIdentity( string $path, IdentityDescriptor $descriptor ): ?array { $facts = $descriptor->toArray(); clearstatcache( true, $path ); $stat = @lstat( $path ); $hash = is_file( $path ) ? hash_file( 'sha256', $path ) : false; if ( ! is_array( $stat ) || 0100000 !== ( $stat['mode'] & 0170000 ) || $stat['size'] !== $facts['artifact_size'] || ! is_string( $hash ) || ! hash_equals( $facts['artifact_sha256'], $hash ) ) return null; return array( 'dev' => $stat['dev'], 'ino' => $stat['ino'], 'mode' => $stat['mode'], 'mtime' => $stat['mtime'], 'ctime' => $stat['ctime'], 'size' => $stat['size'] ); }
	/** @param array<string,int> $identity */ private static function sameArchiveIdentity( string $path, IdentityDescriptor $descriptor, array $identity ): bool { $current = self::archiveIdentity( $path, $descriptor ); if ( ! is_array( $current ) ) return false; foreach ( $identity as $key => $value ) if ( ! array_key_exists( $key, $current ) || $current[ $key ] !== $value ) return false; return true; }
	/** @return array<string,array{sha256:string,size:int}>|null */ private static function regularFileManifest( string $root ): ?array { $root = rtrim( $root, '/\\' ); $rootStat = @lstat( $root ); if ( ! is_array( $rootStat ) || 0040000 !== ( $rootStat['mode'] & 0170000 ) ) return null; $queue = array( array( 'path' => $root, 'relative' => '' ) ); $manifest = array(); $total = 0; $entriesSeen = 0; while ( array() !== $queue ) { $next = array_pop( $queue ); $entries = @scandir( $next['path'] ); if ( ! is_array( $entries ) ) return null; foreach ( $entries as $entry ) { if ( '.' === $entry || '..' === $entry ) continue; if ( ++$entriesSeen > self::MAX_MANIFEST_ENTRIES ) return null; $path = $next['path'] . DIRECTORY_SEPARATOR . $entry; $relative = '' === $next['relative'] ? $entry : $next['relative'] . '/' . $entry; if ( strlen( $relative ) > PackageIdentityValidator::MAX_ARCHIVE_PATH_BYTES || 1 === preg_match( '/[^\x20-\x7E]|[\\\\:]/', $relative ) ) return null; $stat = @lstat( $path ); if ( ! is_array( $stat ) ) return null; $type = $stat['mode'] & 0170000; if ( 0040000 === $type ) { $queue[] = array( 'path' => $path, 'relative' => $relative ); continue; } if ( 0100000 !== $type || $stat['size'] < 0 || $stat['size'] > PackageIdentityValidator::MAX_EXPANDED_ARCHIVE_BYTES - $total ) return null; $hash = @hash_file( 'sha256', $path ); clearstatcache( true, $path ); $after = @lstat( $path ); if ( ! is_string( $hash ) || ! is_array( $after ) || $after['dev'] !== $stat['dev'] || $after['ino'] !== $stat['ino'] || $after['mode'] !== $stat['mode'] || $after['mtime'] !== $stat['mtime'] || $after['ctime'] !== $stat['ctime'] || $after['size'] !== $stat['size'] ) return null; $total += $stat['size']; $manifest[ $relative ] = array( 'sha256' => $hash, 'size' => $stat['size'] ); } } ksort( $manifest, SORT_STRING ); return array() === $manifest ? null : $manifest; }
	/** @param array<string,array{sha256:string,size:int}> $manifest */ private static function manifestHash( array $manifest ): string { return hash( 'sha256', json_encode( $manifest, JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES ) ); }
	/** @param array<string,array{sha256:string,size:int}> $manifest */ private static function manifestExpandedBytes( array $manifest ): int { $total = 0; foreach ( $manifest as $entry ) $total += $entry['size']; return $total; }
	private static function headerValue( string $contents, string $name ): ?string { return 1 === preg_match_all( '/^[ \\t\\/*#@]*' . preg_quote( $name, '/' ) . ':(.*)$/mi', $contents, $matches ) ? trim( $matches[1][0] ) : null; }
	/** @param array<string,mixed> $value @param list<string> $keys */ private static function exactKeys( mixed $value, array $keys ): bool { if ( ! is_array( $value ) || count( $value ) !== count( $keys ) ) return false; foreach ( $keys as $key ) if ( ! array_key_exists( $key, $value ) ) return false; return true; }
}
