name: Release Please

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

permissions: {}

jobs:
  release:
    permissions:
      actions: write
      contents: write
      issues: write
      pull-requests: write
    uses: RocketsAreNostalgic/.github/.github/workflows/release-profile-a.yml@289352e08cdf10b15d07c4e1c890f385afc3d3f5
    with:
      expected-workflow-path: .github/workflows/ci.yml
      release-pr-head: release-please--branches--main--components--ran/wp-release-updater
